model:
  cuda_id: 0
  epoch: 80
  lr: 0.001
  weight_decay: 0.0001
mod:
  use_morgan: true
  use_espf: false
  use_pubchem: false
  use_exp: true
  use_mut: false
  use_meth: true
  use_path: false
enc:
  depth: 4
  mlp_ratio: 4
  dropout: 0.2
ban:
  num_heads: 4
  dropout: 0.1
  gate_init: 1.0
  drop_mode: zero
trans:
  d_model: 128
  nhead: 4
  num_layers: 2
  dim_feedforward: 512
  dropout: 0.3
  pool: gate
  token_dropout: 0.1
mlp:
  mlp_in_dim: 128
  mlp_hidden_dim: [512, 128]

